import type { CharacterData } from '../game/types';

export const characters: Record<string, CharacterData> = {
  player: {
    id: 'player',
    name: 'あなた',
    role: '提出期限ぎりぎりのレポートデータを取りに戻った大学2年生。',
    colorPalette: {
      background: 'var(--color-bg-overlay)',
      skin: 'var(--color-log-ink)',
      hair: 'var(--color-bg-deep)',
      outfit: 'var(--color-accent-blue)',
      accent: 'var(--color-text-secondary)',
      shadow: 'var(--color-border)',
    },
    silhouetteType: 'hooded-backpack',
    faceStyle: 'half-hidden',
    outfit: '暗いパーカー、リュック、少し猫背。',
    expressions: ['neutral', 'worried', 'scared', 'shocked', 'tired', 'silent', 'hidden'],
    mapSprite: 'player',
    portrait: 'hooded portrait',
    horrorVariants: ['flashlight', 'tired', 'blackout'],
    chapterAppearances: {
      prologue: '深夜の入口で輪郭だけが浮く。',
      chapter4: '懐中電灯の光に顔の下半分だけが見える。',
      final: '名前入力を間違えると顔が黒塗りになる。',
    },
  },
  minato: {
    id: 'minato',
    name: 'ミナト',
    role: 'スマホ越しに主人公を心配する友人。',
    colorPalette: {
      background: 'var(--color-bg-surface)',
      skin: 'var(--color-text-secondary)',
      hair: 'var(--color-accent-glow)',
      outfit: 'var(--color-accent-blue)',
      accent: 'var(--color-text-primary)',
      shadow: 'var(--color-border)',
    },
    silhouetteType: 'phone-icon',
    faceStyle: 'soft-but-fragmenting',
    outfit: 'くすんだ青のカジュアル服。',
    expressions: ['neutral', 'worried', 'scared', 'glitched'],
    mapSprite: 'minato',
    portrait: 'smartphone icon',
    horrorVariants: ['noisy-avatar', 'mojibake'],
    chapterAppearances: {
      prologue: '安心できる友人のアイコン。',
      chapter3: '通知の輪郭にノイズが混じる。',
      final: '送信者名が一瞬だけ空欄になる。',
    },
  },
  yu: {
    id: 'yu',
    name: '榊ユウ',
    role: '数年前に失踪し、記録から名前を消された学生。',
    colorPalette: {
      background: 'var(--color-log-paper)',
      skin: 'var(--color-log-ink)',
      hair: 'var(--color-text-muted)',
      outfit: 'var(--color-bg-overlay)',
      accent: 'var(--color-accent-glow)',
      shadow: 'var(--color-danger)',
    },
    silhouetteType: 'recovered-photo',
    faceStyle: 'missing-parts',
    outfit: '古い大学生風の上着と薄いシャツ。',
    expressions: ['hidden', 'silent', 'worried', 'restored'],
    mapSprite: 'yu',
    portrait: 'old student id',
    horrorVariants: ['torn', 'cctv', 'restored'],
    chapterAppearances: {
      chapter1: '名前の消えた学生証だけ。',
      chapter2: '図書館記録のぼやけた写真。',
      chapter3: '防犯映像に映る横顔。',
      chapter4: '破れた写真で輪郭が戻る。',
      final: '正しい名前で完全な姿に近づく。',
    },
  },
  absentee: {
    id: 'absentee',
    name: '欠席者',
    role: '黒い学生の影。敵であり、消された記録の残響。',
    colorPalette: {
      background: 'var(--color-bg-deep)',
      outfit: 'var(--color-bg-deep)',
      accent: 'var(--color-danger)',
      shadow: 'var(--color-border)',
    },
    silhouetteType: 'elongated-shadow',
    faceStyle: 'eyes-only',
    outfit: '制服でも私服でもない、記録に焼き付いた人型。',
    expressions: ['hidden', 'glitched', 'scared', 'restored'],
    mapSprite: 'absentee',
    portrait: 'black shadow',
    horrorVariants: ['distant', 'corridor', 'chase', 'noise', 'memory'],
    chapterAppearances: {
      chapter1: '廊下奥の一瞬の黒い影。',
      chapter2: '書架の間で輪郭だけが残る。',
      chapter3: '目が見える。',
      chapter4: '手足が長く、走る音に反応する。',
      final: '敵ではなく残響として揺らぐ。',
    },
  },
  librarian: {
    id: 'librarian',
    name: '図書館職員の記録',
    role: '失踪事件に気づいていた可能性のある、現在は存在しない記録上の職員。',
    colorPalette: {
      background: 'var(--color-bg-overlay)',
      skin: 'var(--color-log-ink)',
      hair: 'var(--color-text-muted)',
      outfit: 'var(--color-accent-blue)',
      accent: 'var(--color-text-primary)',
      shadow: 'var(--color-border)',
    },
    silhouetteType: 'archival-librarian',
    faceStyle: 'glasses',
    outfit: '司書風の落ち着いた服と眼鏡。',
    expressions: ['neutral', 'worried', 'scared', 'glitched'],
    mapSprite: 'librarian',
    portrait: 'recorded librarian',
    horrorVariants: ['record-video'],
    chapterAppearances: {
      chapter2: '貸出記録の端に小さな写真。',
      chapter4: '地下資料室の回想映像。',
    },
  },
  clerk: {
    id: 'clerk',
    name: '学生課職員の影',
    role: '管理棟を巡回する、本物か残像か曖昧な職員。',
    colorPalette: {
      background: 'var(--color-bg-surface)',
      skin: 'var(--color-text-muted)',
      hair: 'var(--color-bg-deep)',
      outfit: 'var(--color-bg-overlay)',
      accent: 'var(--color-log-ink)',
      shadow: 'var(--color-danger)',
    },
    silhouetteType: 'stiff-office-shadow',
    faceStyle: 'blank',
    outfit: '暗い職員服、首から職員証。',
    expressions: ['neutral', 'silent', 'hidden', 'glitched'],
    mapSprite: 'clerk',
    portrait: 'blank office portrait',
    horrorVariants: ['black-marked', 'turned-back'],
    chapterAppearances: {
      chapter3: '職員用廊下で機械的に巡回する。',
    },
  },
};
