import type { TaskTemplate } from "../types/app";

export const DEFAULT_TEMPLATES: TaskTemplate[] = [
  {
    id: "tpl-report",
    title: "レポート",
    icon: "📝",
    firstStepOptions: [
      "ファイルを開くだけ",
      "タイトルを書くだけ",
      "1行だけ書く",
      "参考資料を1つ開く",
    ],
    colorKey: "blue",
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: "tpl-homework",
    title: "課題",
    icon: "📚",
    firstStepOptions: [
      "問題文を読むだけ",
      "ノートを開くだけ",
      "1問だけ解いてみる",
      "前回の続きを眺める",
    ],
    colorKey: "violet",
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: "tpl-study",
    title: "勉強",
    icon: "🎓",
    firstStepOptions: [
      "教科書を開くだけ",
      "前回の続きを読む",
      "1ページだけ進む",
      "用語を1個だけ調べる",
    ],
    colorKey: "teal",
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: "tpl-reply",
    title: "返信",
    icon: "💬",
    firstStepOptions: [
      "受信箱を開くだけ",
      "1通だけ読む",
      "短い返信を1つ送る",
      "下書きだけ書く",
    ],
    colorKey: "pink",
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: "tpl-tidy",
    title: "片付け",
    icon: "🧺",
    firstStepOptions: [
      "机の上を1つだけ片付ける",
      "ゴミを1つ捨てる",
      "目に入るものを1つ戻す",
      "1か所だけ拭く",
    ],
    colorKey: "amber",
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: "tpl-laundry",
    title: "洗濯",
    icon: "🧺",
    firstStepOptions: [
      "洗濯機の前まで行く",
      "洗濯物を1つ入れる",
      "ボタンを押す",
      "1枚だけたたむ",
    ],
    colorKey: "lime",
    sortOrder: 6,
    isDefault: true,
  },
  {
    id: "tpl-cleaning",
    title: "掃除",
    icon: "🧹",
    firstStepOptions: [
      "掃除機を出す",
      "1か所だけ掃く",
      "床を1m分だけ拭く",
      "ゴミ袋を1つ用意する",
    ],
    colorKey: "rose",
    sortOrder: 7,
    isDefault: true,
  },
  {
    id: "tpl-reading",
    title: "読書",
    icon: "📖",
    firstStepOptions: [
      "本を開くだけ",
      "1ページ読む",
      "目次だけ見る",
      "前回の続きから1段落",
    ],
    colorKey: "slate",
    sortOrder: 8,
    isDefault: true,
  },
  {
    id: "tpl-motivation-letter",
    title: "志望理由書",
    icon: "✍️",
    firstStepOptions: [
      "白紙を用意する",
      "タイトルだけ書く",
      "1文だけ書く",
      "下書きを眺める",
    ],
    colorKey: "blue",
    sortOrder: 9,
    isDefault: true,
  },
  {
    id: "tpl-application",
    title: "面倒な申請",
    icon: "🗂️",
    firstStepOptions: [
      "ページを開くだけ",
      "ログインだけする",
      "1項目だけ埋める",
      "必要書類を1つ確認",
    ],
    colorKey: "violet",
    sortOrder: 10,
    isDefault: true,
  },
];
