import type { Task } from "../types";
import { getTodayDateString, getTomorrowDateString, nowIso } from "./date";
import { genId } from "./storage";

export function buildSampleTasks(): Task[] {
  const today = getTodayDateString();
  const tomorrow = getTomorrowDateString();
  return [
    {
      id: genId(),
      title: "明日の英語課題を進める",
      memo: "Unit 4 の長文読解。15分だけでもOK。",
      category: "大学",
      priority: "高",
      status: "未着手",
      dueDate: tomorrow,
      estimatedMinutes: 30,
      isToday: false,
      planningSource: "前日",
      plannedForDate: tomorrow,
      createdAt: nowIso(),
    },
    {
      id: genId(),
      title: "SPI非言語を15分解く",
      memo: "速さ・濃度のセクション。",
      category: "就活",
      priority: "中",
      status: "未着手",
      dueDate: today,
      estimatedMinutes: 15,
      isToday: true,
      planningSource: "前日",
      plannedForDate: today,
      createdAt: nowIso(),
    },
    {
      id: genId(),
      title: "アプリのUIを1画面改善する",
      memo: "Focus画面の余白を見直す。",
      category: "アプリ開発",
      priority: "中",
      status: "進行中",
      dueDate: today,
      estimatedMinutes: 60,
      isToday: true,
      planningSource: "通常",
      plannedForDate: today,
      createdAt: nowIso(),
    },
    {
      id: genId(),
      title: "夏インターン企業を1社調べる",
      memo: "AI開発系で気になる企業を1つ。",
      category: "就活",
      priority: "中",
      status: "未着手",
      estimatedMinutes: 15,
      isToday: true,
      planningSource: "当日",
      plannedForDate: today,
      createdAt: nowIso(),
    },
    {
      id: genId(),
      title: "部屋を5分片付ける",
      memo: "デスクの上だけでもOK。",
      category: "生活",
      priority: "低",
      status: "未着手",
      estimatedMinutes: 5,
      isToday: true,
      planningSource: "当日",
      plannedForDate: today,
      createdAt: nowIso(),
    },
    {
      id: genId(),
      title: "資格テキスト1章だけ読む",
      memo: "通学中に読める分量で。",
      category: "勉強",
      priority: "低",
      status: "完了",
      estimatedMinutes: 30,
      isToday: false,
      planningSource: "通常",
      plannedForDate: today,
      createdAt: nowIso(),
      completedAt: nowIso(),
    },
  ];
}
