import type { InventoryItem } from './types';

export const items: Record<string, InventoryItem> = {
  student_id: {
    id: 'student_id',
    name: '学生証',
    description: 'あなたの学生証。深夜の校舎では写真だけが少し暗く見える。',
    chapter: 'prologue',
    icon: 'id',
    isImportant: true,
    obtainLocation: '正門前',
  },
  erased_student_id: {
    id: 'erased_student_id',
    name: '名前の消えた学生証',
    description: '氏名欄が黒く削れた学生証。番号は042。',
    chapter: 'chapter1',
    icon: 'id',
    isImportant: true,
    obtainLocation: 'PC室',
  },
  pc_keycard: {
    id: 'pc_keycard',
    name: 'PC室のカードキー',
    description: '講義室Aの机裏に貼られていたカードキー。',
    chapter: 'chapter1',
    icon: 'card',
    isImportant: true,
    obtainLocation: '講義室A',
  },
  library_key: {
    id: 'library_key',
    name: '図書館の鍵',
    description: '1号館の階段前に落ちていた古い鍵。',
    chapter: 'chapter1',
    icon: 'key',
    isImportant: true,
    obtainLocation: '階段前',
  },
  basement_key: {
    id: 'basement_key',
    name: '地下資料室の鍵',
    description: '返却ポストの奥から出てきた鍵。あなたの番号が刻まれている。',
    chapter: 'chapter2',
    icon: 'key',
    isImportant: true,
    obtainLocation: '返却ポスト',
  },
  flashlight: {
    id: 'flashlight',
    name: '懐中電灯',
    description: '地下資料室の入口で拾った小さなライト。光は弱いが、影の動きが少し遅くなる。',
    chapter: 'chapter4',
    icon: 'flashlight',
    isImportant: true,
    obtainLocation: '地下通路',
  },
  torn_photo_a: {
    id: 'torn_photo_a',
    name: '破れた写真A',
    description: '苗字の一部が残った写真。紙の端が冷たい。',
    chapter: 'chapter4',
    icon: 'photo',
    isImportant: true,
    obtainLocation: '記録保管室',
  },
  torn_photo_b: {
    id: 'torn_photo_b',
    name: '破れた写真B',
    description: '名前の一部が残った写真。裏に細い字で「ごめん」とある。',
    chapter: 'chapter4',
    icon: 'photo',
    isImportant: true,
    obtainLocation: '古い掲示板',
  },
  camera_note: {
    id: 'camera_note',
    name: '防犯カメラメモ',
    description: '映像の時刻を書き出したメモ。順番を間違えると、映像内の人影が近づく。',
    chapter: 'chapter3',
    icon: 'camera',
    isImportant: true,
    obtainLocation: '防犯カメラ室',
  },
  attendance_ticket: {
    id: 'attendance_ticket',
    name: '最後の出席票',
    description: '名前を呼ぶための紙。空欄の部分だけ、手で触れると湿っている。',
    chapter: 'final',
    icon: 'ticket',
    isImportant: true,
    obtainLocation: '23:58の教室',
  },
  archive_key: {
    id: 'archive_key',
    name: '保管庫の鍵',
    description: '学生課の隠し保管庫を開いたあとに残った鍵。',
    chapter: 'chapter3',
    icon: 'key',
    isImportant: false,
    obtainLocation: '保管庫',
  },
};
