import type { GameLog } from './types';

export const logs: Record<string, GameLog> = {
  notice_gate: {
    id: 'notice_gate',
    title: '夜間立入禁止の貼り紙',
    body: '正門脇の掲示板に貼られていた紙。印刷された「夜間立入禁止」の下に、乾ききったペンで「まだ出席していない」と書き足されている。',
    chapter: 'prologue',
    isImportant: true,
    relatedPuzzleId: 'final-name',
  },
  message_minato_1: {
    id: 'message_minato_1',
    title: '友人のメッセージ履歴',
    body: 'ミナトからの通知。「まだ大学？終電なくなるぞ」。時刻は23:58で止まったまま、既読だけが増えている。',
    chapter: 'prologue',
    isImportant: false,
  },
  attendance_sheet: {
    id: 'attendance_sheet',
    title: '古い出席表',
    body: '講義室Aの教卓に残っていた出席表。042番だけが黒く塗りつぶされている。欄外には「出席番号は消えない」。',
    chapter: 'chapter1',
    isImportant: true,
    relatedPuzzleId: 'pc-login',
  },
  blackboard_absent: {
    id: 'blackboard_absent',
    title: '本日の欠席者',
    body: '無人の黒板に白い文字が浮かんでいた。「本日の欠席者：1名」。チョークの粉が床ではなく天井に落ちている。',
    chapter: 'chapter1',
    isImportant: false,
  },
  pc_history: {
    id: 'pc_history',
    title: 'PCログイン履歴',
    body: 'PC室の端末に残っていた履歴。最終ログインは student_042。ユーザー名の表示だけが、あなたの学生証番号に重なって見える。',
    chapter: 'chapter1',
    isImportant: true,
    relatedPuzzleId: 'pc-login',
  },
  unsent_mail: {
    id: 'unsent_mail',
    title: '未送信メール',
    body: '件名は「見たなら言って」。本文は途中で途切れている。「屋上前で、君は確かにこちらを見ていた」。送信先は空欄。',
    chapter: 'chapter1',
    isImportant: true,
    relatedPuzzleId: 'final-name',
  },
  erased_id: {
    id: 'erased_id',
    title: '名前の消えた学生証',
    body: '写真の顔は擦れて判別できない。学生番号欄にだけ042の跡が残っている。氏名欄は何度見ても焦点が合わない。',
    chapter: 'chapter1',
    isImportant: true,
  },
  library_card: {
    id: 'library_card',
    title: '図書館貸出カード',
    body: '返却ポスト横のカード。棚番号「B-23」と、同じ筆跡で書かれた「返却日は23:58」。',
    chapter: 'chapter2',
    isImportant: true,
    relatedPuzzleId: 'bookshelf-b23',
  },
  book_b23: {
    id: 'book_b23',
    title: 'B-23の本',
    body: 'B列23番の本。表紙のタイトルは読むたびに変わるが、最後のページだけ同じ。「借りた人が戻らなければ、本も返らない」。',
    chapter: 'chapter2',
    isImportant: false,
    relatedPuzzleId: 'library-clock',
  },
  returned_note: {
    id: 'returned_note',
    title: '返却ポストのメモ',
    body: '「時計を貸出時刻に戻せ。戻らないなら、返せない」。ポストの内側から、爪で引っかいたような音がする。',
    chapter: 'chapter2',
    isImportant: true,
    relatedPuzzleId: 'library-clock',
  },
  librarian_record: {
    id: 'librarian_record',
    title: '図書館職員の記録映像',
    body: '眼鏡の女性職員がカメラに向かっている。「この貸出記録、毎晩いまの時刻で更新されます。学生課に報告します」。映像の最後で背後の棚がひとつ増える。',
    chapter: 'chapter2',
    isImportant: false,
  },
  basement_key_log: {
    id: 'basement_key_log',
    title: '地下資料室の鍵の刻印',
    body: '鍵にはあなたの学生番号が刻まれている。古い傷のように、042の数字だけが指に引っかかる。',
    chapter: 'chapter2',
    isImportant: true,
  },
  student_affairs_black: {
    id: 'student_affairs_black',
    title: '黒塗りの学生課記録',
    body: '失踪者の氏名は黒塗り。ページを閉じる瞬間、あなたの名前の欄も同じ黒で覆われた気がした。',
    chapter: 'chapter3',
    isImportant: true,
    relatedPuzzleId: 'archive-safe',
  },
  camera_1: {
    id: 'camera_1',
    title: '防犯映像メモ1',
    body: '23:12 正門。ひとりが入る。その少し後ろに、画面の圧縮ノイズのような影。',
    chapter: 'chapter3',
    isImportant: false,
    relatedPuzzleId: 'camera-order',
  },
  camera_2: {
    id: 'camera_2',
    title: '防犯映像メモ2',
    body: '23:28 1号館廊下。あなたと似た背中が振り返らないまま歩く。',
    chapter: 'chapter3',
    isImportant: false,
    relatedPuzzleId: 'camera-order',
  },
  camera_3: {
    id: 'camera_3',
    title: '防犯映像メモ3',
    body: '23:41 図書館前。誰かが貸出カードを握っている。顔は黒く潰れているが、袖口に小さな傷。',
    chapter: 'chapter3',
    isImportant: true,
    relatedPuzzleId: 'camera-order',
  },
  camera_4: {
    id: 'camera_4',
    title: '防犯映像メモ4',
    body: '23:55 階段。ふたり分の足音があるのに、映像にはひとりしか映っていない。',
    chapter: 'chapter3',
    isImportant: false,
    relatedPuzzleId: 'camera-order',
  },
  camera_5: {
    id: 'camera_5',
    title: '防犯映像メモ5',
    body: '23:58 屋上前。最後に映った人物は、こちらを見ている。見ていたのはカメラではなく、あなたの方だ。',
    chapter: 'chapter3',
    isImportant: true,
    relatedPuzzleId: 'camera-order',
  },
  locker_key_log: {
    id: 'locker_key_log',
    title: '保管庫の鍵',
    body: '隠し保管庫にあった鍵。タグには「欠席者資料」とだけ書かれている。タグの裏に23:58の刻印。',
    chapter: 'chapter3',
    isImportant: false,
    relatedPuzzleId: 'archive-safe',
  },
  photo_a: {
    id: 'photo_a',
    title: '破れた写真A',
    body: '写真の左半分。苗字の途中だけが見える。「榊」。隣に写る人物の肩は、あなたのパーカーに似ている。',
    chapter: 'chapter4',
    isImportant: true,
    relatedPuzzleId: 'restore-photo',
  },
  photo_b: {
    id: 'photo_b',
    title: '破れた写真B',
    body: '写真の右半分。名前の一部「ユウ」が残っている。顔の欠けた学生は、笑っていたのか泣いていたのかわからない。',
    chapter: 'chapter4',
    isImportant: true,
    relatedPuzzleId: 'restore-photo',
  },
  seminar_roster: {
    id: 'seminar_roster',
    title: '042番のゼミ名簿',
    body: 'ゼミ名簿の042番。氏名欄は空白だが、メモ欄に「榊ユウ、返答なし」。あなたの筆跡に似ている。',
    chapter: 'chapter4',
    isImportant: true,
    relatedPuzzleId: 'final-name',
  },
  basement_record: {
    id: 'basement_record',
    title: '地下資料室の記録',
    body: '古い掲示板の裏に隠されていた記録。「出席確認音は、最後に見た者の記憶を呼ぶ」。',
    chapter: 'chapter4',
    isImportant: false,
    relatedPuzzleId: 'breaker',
  },
  rooftop_security: {
    id: 'rooftop_security',
    title: '屋上前の警備記録',
    body: '23:58、屋上前で非常扉が開いた。記録者欄には黒い長方形。印鑑だけが「榊」と読める。',
    chapter: 'final',
    isImportant: true,
    relatedPuzzleId: 'final-name',
  },
  final_attendance: {
    id: 'final_attendance',
    title: '最後の出席確認票',
    body: '最後の教室に置かれた出席票。「欠席者の名前を呼べ。正しく呼べば、記録は席を返す」。',
    chapter: 'final',
    isImportant: true,
    relatedPuzzleId: 'final-name',
  },
};

export const importantLogIds = Object.values(logs)
  .filter((log) => log.isImportant)
  .map((log) => log.id);
