import type { MapData } from './types';

function room(width = 14, height = 10, openings: Array<'top' | 'right' | 'bottom' | 'left'> = []): string[] {
  return Array.from({ length: height }, (_, y) => {
    return Array.from({ length: width }, (_, x) => {
      const isWall = x === 0 || y === 0 || x === width - 1 || y === height - 1;
      const openTop = openings.includes('top') && y === 0 && x >= Math.floor(width / 2) - 1 && x <= Math.floor(width / 2) + 1;
      const openBottom = openings.includes('bottom') && y === height - 1 && x >= Math.floor(width / 2) - 1 && x <= Math.floor(width / 2) + 1;
      const openLeft = openings.includes('left') && x === 0 && y >= Math.floor(height / 2) - 1 && y <= Math.floor(height / 2) + 1;
      const openRight = openings.includes('right') && x === width - 1 && y >= Math.floor(height / 2) - 1 && y <= Math.floor(height / 2) + 1;
      if (openTop || openBottom || openLeft || openRight) {
        return '.';
      }
      return isWall ? '#' : '.';
    }).join('');
  });
}

export const maps: Record<string, MapData> = {
  gate: {
    id: 'gate',
    name: '大学正門前',
    chapter: 'prologue',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['right']),
    spawn: { x: 5, y: 8 },
    tint: 'prologue',
    objective: '掲示板を調べ、開いている正門へ向かう。',
    points: [
      { id: 'gate_notice', x: 4, y: 4, label: '掲示板', kind: 'log', logId: 'notice_gate', dialogueId: 'gate_notice', radius: 1.6 },
      { id: 'student_id', x: 3, y: 7, label: '学生証', kind: 'item', itemId: 'student_id' },
      { id: 'to_approach', x: 13, y: 5, label: '夜の通学路へ', kind: 'transition', targetMapId: 'approach', targetPosition: { x: 1, y: 5 } },
    ],
  },
  approach: {
    id: 'approach',
    name: '夜の通学路',
    chapter: 'prologue',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'prologue',
    objective: '1号館へ入る。',
    points: [
      { id: 'minato_message', x: 5, y: 5, label: 'スマホ通知', kind: 'log', logId: 'message_minato_1', dialogueId: 'opening', radius: 2, repeatable: true },
      { id: 'back_gate', x: 0, y: 5, label: '正門前へ', kind: 'transition', targetMapId: 'gate', targetPosition: { x: 12, y: 5 } },
      { id: 'to_building1', x: 15, y: 5, label: '1号館へ', kind: 'chapterEnd', targetMapId: 'building1_hall', targetPosition: { x: 1, y: 5 }, requiredLogIds: ['notice_gate'] },
    ],
  },
  building1_hall: {
    id: 'building1_hall',
    name: '1号館廊下',
    chapter: 'chapter1',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['left', 'right', 'top', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter1',
    objective: '講義室AでPC室の手がかりを探す。',
    enemy: { id: 'hall_shadow', characterId: 'absentee', x: 15, y: 3, behavior: 'glimpse', triggerDistance: 4 },
    points: [
      { id: 'to_lecture', x: 8, y: 0, label: '講義室A', kind: 'transition', targetMapId: 'lecture_a', targetPosition: { x: 7, y: 8 } },
      { id: 'to_pc', x: 17, y: 5, label: 'PC室', kind: 'transition', targetMapId: 'pc_room', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['pc_keycard'] },
      { id: 'to_stairs', x: 8, y: 9, label: '階段前', kind: 'transition', targetMapId: 'stairs_1', targetPosition: { x: 7, y: 1 } },
      { id: 'hall_chase', x: 14, y: 3, label: '廊下の奥', kind: 'dialogue', dialogueId: 'chase_intro', repeatable: true },
    ],
  },
  lecture_a: {
    id: 'lecture_a',
    name: '講義室A',
    chapter: 'chapter1',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['bottom']),
    spawn: { x: 7, y: 8 },
    tint: 'chapter1',
    objective: '出席番号の手がかりを見つける。',
    points: [
      { id: 'attendance_sheet', x: 5, y: 4, label: '教卓の出席表', kind: 'log', logId: 'attendance_sheet' },
      { id: 'blackboard', x: 7, y: 1, label: '黒板', kind: 'log', logId: 'blackboard_absent', dialogueId: 'lecture_blackboard', radius: 1.7 },
      { id: 'pc_keycard', x: 10, y: 6, label: '机裏のカード', kind: 'item', itemId: 'pc_keycard' },
      { id: 'back_hall_from_lecture', x: 7, y: 9, label: '廊下へ', kind: 'transition', targetMapId: 'building1_hall', targetPosition: { x: 8, y: 1 } },
    ],
  },
  pc_room: {
    id: 'pc_room',
    name: 'PC室',
    chapter: 'chapter1',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['left']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter1',
    objective: 'student_??? のパスワードでPCにログインする。',
    points: [
      { id: 'pc_terminal', x: 7, y: 4, label: '端末', kind: 'puzzle', puzzleId: 'pc-login', radius: 1.8 },
      { id: 'erased_id_log', x: 10, y: 6, label: '落ちている学生証', kind: 'log', logId: 'erased_id', hiddenUntil: { puzzles: ['pc-login'] } },
      { id: 'back_hall_from_pc', x: 0, y: 5, label: '廊下へ', kind: 'transition', targetMapId: 'building1_hall', targetPosition: { x: 16, y: 5 } },
    ],
  },
  stairs_1: {
    id: 'stairs_1',
    name: '階段前',
    chapter: 'chapter1',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['top', 'right']),
    spawn: { x: 7, y: 1 },
    tint: 'chapter1',
    objective: '図書館入口へ向かう。',
    enemy: { id: 'stair_shadow', characterId: 'absentee', x: 11, y: 7, behavior: 'watch', triggerDistance: 3 },
    points: [
      { id: 'library_key', x: 4, y: 5, label: '古い鍵', kind: 'item', itemId: 'library_key' },
      { id: 'back_hall_from_stairs', x: 7, y: 0, label: '1号館廊下へ', kind: 'transition', targetMapId: 'building1_hall', targetPosition: { x: 8, y: 8 } },
      { id: 'to_library_entrance', x: 13, y: 5, label: '図書館入口', kind: 'transition', targetMapId: 'library_entrance', targetPosition: { x: 1, y: 5 } },
    ],
  },
  library_entrance: {
    id: 'library_entrance',
    name: '図書館入口',
    chapter: 'chapter1',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter1',
    objective: 'PCログイン後、図書館の鍵で中へ入る。',
    points: [
      { id: 'library_entry_locked', x: 7, y: 5, label: '施錠された扉', kind: 'dialogue', dialogueId: 'ch1_clear', repeatable: true },
      { id: 'back_stairs_from_library', x: 0, y: 5, label: '階段前へ', kind: 'transition', targetMapId: 'stairs_1', targetPosition: { x: 12, y: 5 } },
      { id: 'to_library_lobby', x: 13, y: 5, label: '図書館へ', kind: 'chapterEnd', targetMapId: 'library_lobby', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['library_key'], requiredPuzzleIds: ['pc-login'] },
    ],
  },
  library_lobby: {
    id: 'library_lobby',
    name: '図書館ロビー',
    chapter: 'chapter2',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter2',
    objective: '貸出カードから本棚番号を探す。',
    points: [
      { id: 'library_intro', x: 3, y: 5, label: '動く時計', kind: 'dialogue', dialogueId: 'library_entry', repeatable: true },
      { id: 'library_card', x: 6, y: 3, label: '貸出カード', kind: 'log', logId: 'library_card' },
      { id: 'to_stacks', x: 15, y: 5, label: '書架エリア', kind: 'transition', targetMapId: 'stacks', targetPosition: { x: 1, y: 5 } },
      { id: 'to_reading', x: 8, y: 9, label: '閲覧席', kind: 'transition', targetMapId: 'reading_area', targetPosition: { x: 7, y: 1 } },
    ],
  },
  stacks: {
    id: 'stacks',
    name: '書架エリア',
    chapter: 'chapter2',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter2',
    objective: 'B-23の本を見つける。走らない。',
    enemy: { id: 'stack_shadow', characterId: 'absentee', x: 14, y: 4, behavior: 'watch', triggerDistance: 5 },
    points: [
      { id: 'hide_event', x: 5, y: 6, label: '机の下', kind: 'dialogue', dialogueId: 'hide_event', repeatable: true },
      { id: 'b23_shelf', x: 11, y: 3, label: 'B列23番', kind: 'puzzle', puzzleId: 'bookshelf-b23', requiredLogIds: ['library_card'] },
      { id: 'back_lobby_from_stacks', x: 0, y: 5, label: 'ロビーへ', kind: 'transition', targetMapId: 'library_lobby', targetPosition: { x: 14, y: 5 } },
      { id: 'to_return_post', x: 17, y: 5, label: '返却ポスト', kind: 'transition', targetMapId: 'return_post', targetPosition: { x: 1, y: 5 }, requiredPuzzleIds: ['bookshelf-b23'] },
    ],
  },
  reading_area: {
    id: 'reading_area',
    name: '閲覧席',
    chapter: 'chapter2',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['top']),
    spawn: { x: 7, y: 1 },
    tint: 'chapter2',
    objective: '職員の記録を確認する。',
    npcs: [{ id: 'librarian_record_npc', characterId: 'librarian', x: 8, y: 5, dialogueId: 'b23_found', expression: 'worried' }],
    points: [
      { id: 'librarian_record', x: 8, y: 5, label: '古い映像', kind: 'log', logId: 'librarian_record', radius: 1.6 },
      { id: 'back_lobby_from_reading', x: 7, y: 0, label: 'ロビーへ', kind: 'transition', targetMapId: 'library_lobby', targetPosition: { x: 8, y: 8 } },
    ],
  },
  return_post: {
    id: 'return_post',
    name: '返却ポスト',
    chapter: 'chapter2',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter2',
    objective: '時計を23:58に合わせ、返却ポストを開く。',
    points: [
      { id: 'clock_puzzle', x: 7, y: 4, label: '図書館時計', kind: 'puzzle', puzzleId: 'library-clock', requiredPuzzleIds: ['bookshelf-b23'] },
      { id: 'back_stacks_from_post', x: 0, y: 5, label: '書架へ', kind: 'transition', targetMapId: 'stacks', targetPosition: { x: 16, y: 5 } },
      { id: 'to_basement_entrance', x: 13, y: 5, label: '地下資料室入口', kind: 'transition', targetMapId: 'basement_entrance', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['basement_key'] },
    ],
  },
  basement_entrance: {
    id: 'basement_entrance',
    name: '地下資料室入口',
    chapter: 'chapter2',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter2',
    objective: '学生課・管理棟へ向かい、記録を確認する。',
    points: [
      { id: 'back_return_post', x: 0, y: 5, label: '返却ポストへ', kind: 'transition', targetMapId: 'return_post', targetPosition: { x: 12, y: 5 } },
      { id: 'to_affairs', x: 13, y: 5, label: '管理棟へ', kind: 'chapterEnd', targetMapId: 'affairs_front', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['basement_key'] },
    ],
  },
  affairs_front: {
    id: 'affairs_front',
    name: '学生課前',
    chapter: 'chapter3',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter3',
    objective: '学生課の黒塗り記録と防犯映像を確認する。',
    npcs: [{ id: 'clerk_front', characterId: 'clerk', x: 9, y: 4, dialogueId: 'affairs_entry', expression: 'silent' }],
    points: [
      { id: 'affairs_dialogue', x: 9, y: 4, label: '職員の影', kind: 'dialogue', dialogueId: 'affairs_entry', repeatable: true },
      { id: 'black_record', x: 5, y: 3, label: '学生課記録', kind: 'log', logId: 'student_affairs_black' },
      { id: 'to_office', x: 15, y: 5, label: '事務室', kind: 'transition', targetMapId: 'office', targetPosition: { x: 1, y: 5 } },
      { id: 'to_staff_corridor', x: 8, y: 9, label: '職員用廊下', kind: 'transition', targetMapId: 'staff_corridor', targetPosition: { x: 7, y: 1 } },
    ],
  },
  office: {
    id: 'office',
    name: '事務室',
    chapter: 'chapter3',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter3',
    objective: '防犯カメラ室で映像順を整理する。',
    points: [
      { id: 'camera1', x: 5, y: 3, label: '正門映像', kind: 'log', logId: 'camera_1' },
      { id: 'camera2', x: 6, y: 5, label: '廊下映像', kind: 'log', logId: 'camera_2' },
      { id: 'camera3', x: 7, y: 7, label: '図書館前映像', kind: 'log', logId: 'camera_3' },
      { id: 'back_affairs_from_office', x: 0, y: 5, label: '学生課前へ', kind: 'transition', targetMapId: 'affairs_front', targetPosition: { x: 14, y: 5 } },
      { id: 'to_camera_room', x: 15, y: 5, label: '防犯カメラ室', kind: 'transition', targetMapId: 'camera_room', targetPosition: { x: 1, y: 5 }, requiredLogIds: ['camera_1', 'camera_2', 'camera_3'] },
      { id: 'to_archive_room', x: 8, y: 9, label: '保管庫', kind: 'transition', targetMapId: 'archive_room', targetPosition: { x: 7, y: 1 }, requiredPuzzleIds: ['camera-order'] },
    ],
  },
  camera_room: {
    id: 'camera_room',
    name: '防犯カメラ室',
    chapter: 'chapter3',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['left']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter3',
    objective: '防犯映像を時刻順に並べる。',
    points: [
      { id: 'camera_order', x: 7, y: 5, label: '映像編集卓', kind: 'puzzle', puzzleId: 'camera-order', requiredLogIds: ['camera_1', 'camera_2', 'camera_3'] },
      { id: 'back_office_from_camera', x: 0, y: 5, label: '事務室へ', kind: 'transition', targetMapId: 'office', targetPosition: { x: 14, y: 5 } },
    ],
  },
  archive_room: {
    id: 'archive_room',
    name: '保管庫',
    chapter: 'chapter3',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['top']),
    spawn: { x: 7, y: 1 },
    tint: 'chapter3',
    objective: '23:58を使い、隠し保管庫を開く。',
    points: [
      { id: 'safe_puzzle', x: 7, y: 5, label: '隠し保管庫', kind: 'puzzle', puzzleId: 'archive-safe', requiredPuzzleIds: ['camera-order'] },
      { id: 'back_office_from_archive', x: 7, y: 0, label: '事務室へ', kind: 'transition', targetMapId: 'office', targetPosition: { x: 8, y: 8 } },
    ],
  },
  staff_corridor: {
    id: 'staff_corridor',
    name: '職員用廊下',
    chapter: 'chapter3',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['top', 'right']),
    spawn: { x: 7, y: 1 },
    tint: 'chapter3',
    objective: '音を立てずに地下資料室へ向かう。',
    enemy: {
      id: 'clerk_patrol',
      characterId: 'absentee',
      x: 13,
      y: 5,
      behavior: 'patrol',
      triggerDistance: 4,
      patrol: [
        { x: 13, y: 5 },
        { x: 15, y: 7 },
        { x: 10, y: 7 },
      ],
    },
    points: [
      { id: 'stealth_tip', x: 7, y: 3, label: '低い声', kind: 'dialogue', dialogueId: 'stealth_warning', repeatable: true },
      { id: 'back_affairs_from_corridor', x: 7, y: 0, label: '学生課前へ', kind: 'transition', targetMapId: 'affairs_front', targetPosition: { x: 8, y: 8 } },
      { id: 'to_basement_corridor', x: 17, y: 5, label: '地下通路へ', kind: 'chapterEnd', targetMapId: 'basement_corridor', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['archive_key'] },
    ],
  },
  basement_corridor: {
    id: 'basement_corridor',
    name: '地下通路',
    chapter: 'chapter4',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['left', 'right', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter4',
    objective: '懐中電灯を拾い、資料室の記録を探す。',
    enemy: { id: 'basement_shadow', characterId: 'absentee', x: 14, y: 4, behavior: 'watch', triggerDistance: 5 },
    points: [
      { id: 'basement_intro', x: 3, y: 5, label: '地下の空気', kind: 'dialogue', dialogueId: 'basement_entry', repeatable: true },
      { id: 'flashlight_item', x: 5, y: 6, label: '懐中電灯', kind: 'item', itemId: 'flashlight' },
      { id: 'to_record_storage', x: 17, y: 5, label: '記録保管室', kind: 'transition', targetMapId: 'record_storage', targetPosition: { x: 1, y: 5 }, requiredItemIds: ['flashlight'] },
      { id: 'to_blackout', x: 9, y: 9, label: '停電した資料室', kind: 'transition', targetMapId: 'blackout_archive', targetPosition: { x: 7, y: 1 }, requiredItemIds: ['flashlight'] },
    ],
  },
  record_storage: {
    id: 'record_storage',
    name: '記録保管室',
    chapter: 'chapter4',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter4',
    objective: '破れた写真の片方を回収する。',
    points: [
      { id: 'photo_a_log', x: 6, y: 4, label: '写真A', kind: 'log', logId: 'photo_a' },
      { id: 'photo_a_item', x: 7, y: 4, label: '破れた写真A', kind: 'item', itemId: 'torn_photo_a' },
      { id: 'back_basement_from_record', x: 0, y: 5, label: '地下通路へ', kind: 'transition', targetMapId: 'basement_corridor', targetPosition: { x: 16, y: 5 } },
      { id: 'to_old_board', x: 15, y: 5, label: '古い掲示板', kind: 'transition', targetMapId: 'old_board', targetPosition: { x: 1, y: 5 } },
    ],
  },
  old_board: {
    id: 'old_board',
    name: '古い掲示板',
    chapter: 'chapter4',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter4',
    objective: '写真の残りと掲示板の記録を確認する。',
    points: [
      { id: 'photo_b_log', x: 6, y: 5, label: '写真B', kind: 'log', logId: 'photo_b' },
      { id: 'photo_b_item', x: 7, y: 5, label: '破れた写真B', kind: 'item', itemId: 'torn_photo_b' },
      { id: 'restore_photo', x: 10, y: 4, label: '写真を重ねる', kind: 'puzzle', puzzleId: 'restore-photo', requiredItemIds: ['torn_photo_a', 'torn_photo_b'] },
      { id: 'back_record_from_board', x: 0, y: 5, label: '記録保管室へ', kind: 'transition', targetMapId: 'record_storage', targetPosition: { x: 14, y: 5 } },
      { id: 'to_emergency', x: 15, y: 5, label: '非常階段', kind: 'transition', targetMapId: 'emergency_stairs', targetPosition: { x: 1, y: 5 }, requiredPuzzleIds: ['restore-photo', 'breaker'] },
    ],
  },
  blackout_archive: {
    id: 'blackout_archive',
    name: '停電した資料室',
    chapter: 'chapter4',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['top']),
    spawn: { x: 7, y: 1 },
    tint: 'chapter4',
    objective: 'ブレーカーを復旧し、掲示板の記録を読む。',
    points: [
      { id: 'breaker_puzzle', x: 7, y: 5, label: '配電盤', kind: 'puzzle', puzzleId: 'breaker' },
      { id: 'back_basement_from_blackout', x: 7, y: 0, label: '地下通路へ', kind: 'transition', targetMapId: 'basement_corridor', targetPosition: { x: 9, y: 8 } },
    ],
  },
  emergency_stairs: {
    id: 'emergency_stairs',
    name: '非常階段',
    chapter: 'chapter4',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'chapter4',
    objective: '追跡を振り切り、屋上前へ向かう。',
    enemy: { id: 'big_chase_shadow', characterId: 'absentee', x: 5, y: 5, behavior: 'chase', triggerDistance: 10 },
    points: [
      { id: 'big_chase_dialogue', x: 3, y: 5, label: '背後の足音', kind: 'dialogue', dialogueId: 'big_chase', repeatable: true },
      { id: 'back_board_from_stairs', x: 0, y: 5, label: '古い掲示板へ', kind: 'transition', targetMapId: 'old_board', targetPosition: { x: 14, y: 5 } },
      { id: 'to_rooftop_front', x: 17, y: 5, label: '屋上前へ', kind: 'chapterEnd', targetMapId: 'rooftop_front', targetPosition: { x: 1, y: 5 }, requiredPuzzleIds: ['restore-photo', 'breaker'] },
    ],
  },
  rooftop_front: {
    id: 'rooftop_front',
    name: '屋上前',
    chapter: 'final',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right', 'bottom']),
    spawn: { x: 1, y: 5 },
    tint: 'final',
    objective: '屋上前の警備記録を確認し、23:58の教室へ向かう。',
    enemy: { id: 'memory_shadow', characterId: 'absentee', x: 12, y: 5, behavior: 'memory', triggerDistance: 6 },
    points: [
      { id: 'final_intro', x: 4, y: 5, label: '変わる扉', kind: 'dialogue', dialogueId: 'final_entry', repeatable: true },
      { id: 'rooftop_security', x: 7, y: 4, label: '警備記録', kind: 'log', logId: 'rooftop_security' },
      { id: 'to_rooftop', x: 8, y: 9, label: '屋上', kind: 'transition', targetMapId: 'rooftop', targetPosition: { x: 7, y: 1 } },
      { id: 'to_classroom', x: 15, y: 5, label: '23:58の教室', kind: 'transition', targetMapId: 'classroom_2358', targetPosition: { x: 1, y: 5 }, requiredLogIds: ['rooftop_security'] },
    ],
  },
  rooftop: {
    id: 'rooftop',
    name: '屋上',
    chapter: 'final',
    width: 14,
    height: 10,
    tiles: room(14, 10, ['top']),
    spawn: { x: 7, y: 1 },
    tint: 'final',
    objective: '記録の中の廊下へ戻る。',
    points: [
      { id: 'roof_memory', x: 7, y: 5, label: '風のない屋上', kind: 'dialogue', dialogueId: 'ch4_clear', repeatable: true },
      { id: 'back_rooftop_front', x: 7, y: 0, label: '屋上前へ', kind: 'transition', targetMapId: 'rooftop_front', targetPosition: { x: 8, y: 8 } },
    ],
  },
  classroom_2358: {
    id: 'classroom_2358',
    name: '23:58の教室',
    chapter: 'final',
    width: 16,
    height: 10,
    tiles: room(16, 10, ['left', 'right']),
    spawn: { x: 1, y: 5 },
    tint: 'final',
    objective: '最後の出席確認票を調べ、名前を入力する。',
    npcs: [{ id: 'yu_memory', characterId: 'yu', x: 10, y: 5, expression: 'hidden' }],
    points: [
      { id: 'final_attendance_log', x: 6, y: 4, label: '最後の出席確認票', kind: 'log', logId: 'final_attendance' },
      { id: 'attendance_ticket_item', x: 7, y: 4, label: '出席票', kind: 'item', itemId: 'attendance_ticket' },
      { id: 'final_name', x: 10, y: 5, label: '名前を書く', kind: 'puzzle', puzzleId: 'final-name', requiredLogIds: ['final_attendance'] },
      { id: 'back_rooftop_front_from_class', x: 0, y: 5, label: '屋上前へ', kind: 'transition', targetMapId: 'rooftop_front', targetPosition: { x: 14, y: 5 } },
      { id: 'to_record_corridor', x: 15, y: 5, label: '記録の中の廊下', kind: 'transition', targetMapId: 'record_corridor', targetPosition: { x: 1, y: 5 }, requiredPuzzleIds: ['final-name'] },
    ],
  },
  record_corridor: {
    id: 'record_corridor',
    name: '記録の中の廊下',
    chapter: 'final',
    width: 18,
    height: 10,
    tiles: room(18, 10, ['left']),
    spawn: { x: 1, y: 5 },
    tint: 'final',
    objective: 'エンディングへ進む。',
    enemy: { id: 'final_memory', characterId: 'absentee', x: 12, y: 5, behavior: 'memory', triggerDistance: 6 },
    points: [
      { id: 'ending_point', x: 12, y: 5, label: '23:59へ', kind: 'ending', radius: 2 },
      { id: 'back_classroom_from_record', x: 0, y: 5, label: '23:58の教室へ', kind: 'transition', targetMapId: 'classroom_2358', targetPosition: { x: 14, y: 5 } },
    ],
  },
};
