import type { PuzzleData } from './types';

export const puzzles: Record<string, PuzzleData> = {
  'pc-login': {
    id: 'pc-login',
    title: 'PCログインパスワード',
    kind: 'password',
    chapter: 'chapter1',
    prompt: '端末は student_??? の形式を要求している。',
    prefix: 'student_',
    placeholder: '042',
    answer: 'student_042',
    hints: ['講義室Aの黒板を見る。', '出席表では042だけが黒塗り。', 'student_042 と入力する。'],
    rewardLogs: ['pc_history', 'unsent_mail'],
    rewardItems: ['erased_student_id'],
    successDialogueId: 'pc_unlocked',
    failureText: 'カーソルが一瞬だけ「欠席」と表示された。',
  },
  'bookshelf-b23': {
    id: 'bookshelf-b23',
    title: '図書館の本棚番号',
    kind: 'code',
    chapter: 'chapter2',
    prompt: '貸出カードの棚番号を入力する。',
    placeholder: 'B-23',
    answer: 'B-23',
    hints: ['返却ポスト横に貸出カードがある。', 'カードにはB-23と書かれている。', 'B-23 と入力する。'],
    rewardLogs: ['book_b23'],
    successDialogueId: 'b23_found',
  },
  'library-clock': {
    id: 'library-clock',
    title: '時計を23:58に合わせる',
    kind: 'clock',
    chapter: 'chapter2',
    prompt: '図書館時計の針を返却日の時刻に合わせる。',
    answer: '23:58',
    hints: ['B-23の本の最後のページ。', '返却日は23:58。', '時計を23:58に合わせる。'],
    rewardLogs: ['returned_note', 'basement_key_log'],
    rewardItems: ['basement_key'],
    successDialogueId: 'clock_opened',
  },
  'camera-order': {
    id: 'camera-order',
    title: '防犯カメラ時系列',
    kind: 'sequence',
    chapter: 'chapter3',
    prompt: '映像を時刻順に並べ替える。',
    answer: ['gate', 'hall', 'library', 'stairs', 'rooftop'],
    hints: ['メモは時刻を含んでいる。', '23:12から23:58へ並べる。', '正門、1号館廊下、図書館前、階段、屋上前。'],
    options: [
      { id: 'hall', label: '23:28  1号館廊下' },
      { id: 'gate', label: '23:12  正門' },
      { id: 'stairs', label: '23:55  階段' },
      { id: 'library', label: '23:41  図書館前' },
      { id: 'rooftop', label: '23:58  屋上前' },
    ],
    rewardLogs: ['camera_4', 'camera_5'],
    rewardItems: ['camera_note'],
    successDialogueId: 'camera_sorted',
  },
  'archive-safe': {
    id: 'archive-safe',
    title: '保管庫の暗証番号',
    kind: 'code',
    chapter: 'chapter3',
    prompt: '隠し保管庫は4桁の時刻を求めている。',
    placeholder: '2358',
    answer: '2358',
    hints: ['すべての記録が同じ時刻に戻る。', '時計が止まるのは23:58。', '2358 と入力する。'],
    rewardLogs: ['locker_key_log'],
    rewardItems: ['archive_key'],
    successDialogueId: 'safe_opened',
  },
  breaker: {
    id: 'breaker',
    title: '停電中のブレーカー復旧',
    kind: 'breaker',
    chapter: 'chapter4',
    prompt: '古い配電盤。掲示板の記録通りに上げ下げする。',
    answer: '1011',
    hints: ['地下資料室の記録に「点・消・点・点」。', '1つ目、3つ目、4つ目をON。', 'ON / OFF / ON / ON にする。'],
    rewardLogs: ['basement_record'],
    successDialogueId: 'breaker_on',
  },
  'restore-photo': {
    id: 'restore-photo',
    title: '写真の復元',
    kind: 'photo',
    chapter: 'chapter4',
    prompt: '破れた写真、出席表、貸出記録を重ねて名前を復元する。',
    answer: '榊ユウ',
    hints: ['写真Aには苗字が残る。', '写真Bには名前が残る。', '榊ユウ。'],
    rewardLogs: ['seminar_roster'],
    successDialogueId: 'photo_restored',
  },
  'final-name': {
    id: 'final-name',
    title: '最後の名前入力',
    kind: 'name',
    chapter: 'final',
    prompt: '最後の出席確認票に、欠席者の名前を書く。',
    placeholder: '名前',
    answer: ['榊ユウ', '榊ゆう', 'さかきゆう', 'sakaki yu', 'SAKAKI YU'],
    hints: ['重要ログは名前の断片を持っている。', '写真Aは榊、写真Bはユウ。', '榊ユウ と入力する。'],
    rewardLogs: ['final_attendance'],
    rewardItems: ['attendance_ticket'],
    successDialogueId: 'final_correct',
    failureText: '紙が黒く滲み、あなたの名前の上に042が重なる。',
  },
};
